#!/bin/bash
# Build uImage.flasher: the production FH8856 kernel plus an embedded initramfs
# whose /init is the static network flasher.
#
# The production kernel config is restored afterwards, so this never changes
# what `make BOARD=fh8856v100_lite` produces.
set -euo pipefail

ROOT=/home/kasperi/Desktop/OpenIPC
FW=$ROOT/src/firmware/output-v100
KDIR=$FW/build/linux-custom
HOSTBIN=$FW/host/bin
IMG=$FW/images
HERE=$ROOT/initramfs
STAGE=$HERE/root
LOADADDR=0xa0008000

export PATH="$HOSTBIN:$PATH"
export ARCH=arm
export CROSS_COMPILE=arm-openipc-linux-musleabi-

echo "=== 1. bake image sizes/crc32 into images.h ==="
python3 - "$IMG" <<'PYEOF'
import sys, os, zlib
img = sys.argv[1]; out = []
for tag, name in (("KERNEL","uImage.fh8856v100"), ("ROOTFS","rootfs.squashfs.fh8856v100")):
    d = open(os.path.join(img, name), "rb").read()
    out += ['#define IMG_%s_NAME "%s"' % (tag, name),
            '#define IMG_%s_SIZE %dL' % (tag, len(d)),
            '#define IMG_%s_CRC 0x%08xUL' % (tag, zlib.crc32(d) & 0xFFFFFFFF)]
# The env carries its own crc32 and is validated against that, not a baked
# constant -- it differs per camera by ethaddr, and one flasher image should
# serve every unit.
out.append('#define IMG_ENV_NAME "env.bin"')
open("images.h", "w").write("/* generated by build_flasher.sh - do not edit */\n"
                            + "\n".join(out) + "\n")
print("\n".join(out))
PYEOF

echo "=== 2. compile the static flasher ==="
cd "$HERE"
# Network parameters are compiled in. Use an argv array, not eval: eval strips
# the quotes and gcc then sees -DCAM_IP=192.168.2.130, which is not a string.
NETDEFS=()
[ -n "${CAM_IP:-}" ]    && NETDEFS+=(-DCAM_IP=\"$CAM_IP\")
[ -n "${SRV_IP:-}" ]    && NETDEFS+=(-DSRV_IP=\"$SRV_IP\")
[ -n "${GW_IP:-}" ]     && NETDEFS+=(-DGW_IP=\"$GW_IP\")
[ -n "${NETMASK:-}" ]   && NETDEFS+=(-DNETMASK=\"$NETMASK\")
[ -n "${TFTP_PORT:-}" ] && NETDEFS+=(-DTFTP_PORT=$TFTP_PORT)
echo "net defines: ${NETDEFS[@]+${NETDEFS[@]}}"
${CROSS_COMPILE}gcc -static -Os -Wall -Wextra ${NETDEFS[@]+"${NETDEFS[@]}"} -o init flasher.c
${CROSS_COMPILE}strip init
ls -l init

echo "=== 3. stage the initramfs ==="
rm -rf "$STAGE"
mkdir -p "$STAGE"/{dev,proc,sys}
cp init "$STAGE"/init
chmod 755 "$STAGE"/init

echo "=== 4. build the kernel with that initramfs ==="
cd "$KDIR"
cp -a .config "$HERE/.config.production"          # restored in the trap below
trap 'cp -a "$HERE/.config.production" "$KDIR/.config"; echo "[production .config restored]"' EXIT

sed -i 's|^CONFIG_INITRAMFS_SOURCE=.*|CONFIG_INITRAMFS_SOURCE="'"$STAGE"'"|' .config
grep -n "CONFIG_INITRAMFS_SOURCE" .config
yes "" | make oldconfig >/dev/null 2>&1 || true
grep -n "CONFIG_INITRAMFS_SOURCE" .config

make -j"$(nproc)" uImage LOADADDR=$LOADADDR 2>&1 | tail -12

echo "=== 5. collect ==="
OUT=$ROOT/tftproot/uImage.flasher
cp arch/arm/boot/uImage "$OUT"
cp "$OUT" "$IMG/uImage.flasher"
SZ=$(stat -c%s "$OUT")
echo "uImage.flasher = $SZ bytes"
python3 - "$SZ" <<'PYEOF'
import sys
sz = int(sys.argv[1]); slot = 0x200000
print("kernel slot 2048K = %d bytes" % slot)
if sz <= slot:
    print("FITS with %d bytes (%.0f KB) to spare" % (slot - sz, (slot - sz) / 1024.0))
else:
    print("!! TOO BIG by %d bytes - it would run past 0x250000 into the rootfs region" % (sz - slot))
    sys.exit(1)
PYEOF
